name: newman-api-tests

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  api-tests:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        with:
          node-version: 22.14.0
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
      - name: Run newman tests
        run: npm run test
      - uses: actions/upload-artifact@v4
        if: always()
        continue-on-error: true
        with:
          name: newman-report
          path: newman/
          retention-days: 7
      - name: Deploy report to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_branch: gh-pages
          publish_dir: newman
